packages:
  - apps/*
  - libs/*

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - oxc-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@posthog/cli'
  - '@sentry/cli'
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
